#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoereInNood.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FarmerInNeeed")]
	public partial class FarmersInNeedDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FarmersInNeedDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FarmerInNeeedConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FarmersInNeedDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FarmersInNeedDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FarmersInNeedDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FarmersInNeedDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetHeroes")]
		public ISingleResult<sp_GetHeroesResult> sp_GetHeroes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_GetHeroesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetUserMessages")]
		public ISingleResult<sp_GetUserMessagesResult> sp_GetUserMessages([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> memberid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), memberid);
			return ((ISingleResult<sp_GetUserMessagesResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_GetHeroesResult
	{
		
		private int _HeroID;
		
		private string _Message;
		
		private System.Nullable<System.DateTime> _DateEntry;
		
		public sp_GetHeroesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeroID", DbType="Int NOT NULL")]
		public int HeroID
		{
			get
			{
				return this._HeroID;
			}
			set
			{
				if ((this._HeroID != value))
				{
					this._HeroID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(MAX)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateEntry", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateEntry
		{
			get
			{
				return this._DateEntry;
			}
			set
			{
				if ((this._DateEntry != value))
				{
					this._DateEntry = value;
				}
			}
		}
	}
	
	public partial class sp_GetUserMessagesResult
	{
		
		private int _UserMessageID;
		
		private string _MessageText;
		
		private System.DateTime _DateInserted;
		
		public sp_GetUserMessagesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserMessageID", DbType="Int NOT NULL")]
		public int UserMessageID
		{
			get
			{
				return this._UserMessageID;
			}
			set
			{
				if ((this._UserMessageID != value))
				{
					this._UserMessageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageText", DbType="VarChar(MAX)")]
		public string MessageText
		{
			get
			{
				return this._MessageText;
			}
			set
			{
				if ((this._MessageText != value))
				{
					this._MessageText = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateInserted", DbType="DateTime NOT NULL")]
		public System.DateTime DateInserted
		{
			get
			{
				return this._DateInserted;
			}
			set
			{
				if ((this._DateInserted != value))
				{
					this._DateInserted = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
